### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by ubcent** [maestro881/js#1]
1. [L78](https://github.com/maestro881/js/blob/master/lesson%202/1/js.js#L78) Странное условие. Можно написать проще.
2. [L100](https://github.com/maestro881/js/blob/master/lesson%202/1/js.js#L100) Объясните назначение данного метода.
3. [L17](https://github.com/maestro881/js/blob/master/lesson%203/2/index.html#L17) попробуйте сделать тоже самое с помощью [$.each](http://api.jquery.com/jquery.each/)
4. [L27](https://github.com/maestro881/js/blob/master/lesson%203/4/index.html#L27) оборачивается сам li, а должно оборачиваться его содержимое.

**Comment by maestro881** [comment]
L17 и  L27 исправил.
L78 я так и не смог написать проще. 
L100 - у меня было изначально другая задумка и просто забыл удалить.

И еще есть вопрос: в шахматах когда передвигаешься  по ячейкам  рамка остается.

**Comment by ubcent** [comment]
[L16](https://github.com/maestro881/js/blob/master/lesson%202/1/js.js#L16) вот тут нужно у старого элемента снять выделение:
```javascript
this.lastElem.style.outline = 'none';
this.lastElem = event.srcElement;
```

**Comment by maestro881** [comment]
ясно, 
спасибо
